// <auto-generated />
using System;
using GenericCourses.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GenericCourses.Infra.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240128143510_noIdentity")]
    partial class noIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseProgress", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("done")
                        .HasColumnType("boolean");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.HasIndex("userId");

                    b.ToTable("CourseProgresses");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Courseid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Postid")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Courseid");

                    b.HasIndex("Postid");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("courseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("emited_at")
                        .HasColumnType("Date");

                    b.HasKey("id");

                    b.ToTable("certificates");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("Date");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("duration")
                        .HasColumnType("text");

                    b.Property<string>("instrutor")
                        .HasColumnType("text");

                    b.Property<bool>("isFree")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastupdate")
                        .HasColumnType("Date");

                    b.Property<string>("thumb")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("complete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("courseId")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("acesses")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("Date");

                    b.Property<string>("text")
                        .HasColumnType("text");

                    b.Property<string>("thumb")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<Guid?>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("posts");

                    b.HasData(
                        new
                        {
                            id = new Guid("babd8e60-dc9f-4371-a2c8-903537868bfb"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 662, DateTimeKind.Local).AddTicks(6663),
                            text = "Quo incidunt nobis adipisci ut nemo. Eos et eos aut vitae consequuntur delectus et unde. Commodi autem sit voluptatum maiores quas eum ea doloribus. Nulla voluptas voluptatem nam rerum modi. Et id est voluptatem sint.",
                            title = "Sabonete",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("1a3f5343-683e-46eb-af3c-e31ecabdeaeb"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(900),
                            text = "Rerum ipsam qui veritatis corporis impedit sit.\nVeritatis fugiat sequi.",
                            title = "Sapatos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("fc755809-a1c0-4300-860e-b0ae8c45bae7"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1042),
                            text = "cupiditate",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("495cfd3e-de08-41aa-bb59-daddff4641ca"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1069),
                            text = "Quod aliquid ipsa deleniti. Qui aut commodi. A voluptate laboriosam qui ut. Non natus sint eos ratione omnis eligendi voluptas. Libero quasi velit iure.",
                            title = "Salsicha",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("41e5b521-7083-4378-98c7-2f7c73d7ff5a"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1256),
                            text = "Et dolor asperiores vero qui delectus ex.",
                            title = "Salgadinhos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("31a18912-31e7-4887-9dbd-f019248f8ad9"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1312),
                            text = "ex",
                            title = "Mesa",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("ed267020-6622-4998-a032-2d83eb4ff06e"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1336),
                            text = "Voluptates qui est repudiandae.\nDoloribus sint voluptas ut eum.\nItaque corrupti impedit quae voluptas.\nIusto dolores quisquam architecto eum.",
                            title = "Computador",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("ac9c6fb4-e01c-43d8-8aae-04f429a9db1c"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1488),
                            text = "dignissimos",
                            title = "Bicicleta",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("cb10bf83-e820-4d1a-b9ed-3320554f814e"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1515),
                            text = "Minus nostrum provident dolorem soluta autem iste possimus molestiae quis. Et dolorum omnis qui omnis. Totam aut illum eum ea quidem nemo vel sint. Illum repudiandae exercitationem quia repellendus alias necessitatibus et neque quas. Officia ut rerum tenetur aut error est. Officia adipisci sint ut ea quia quis excepturi porro reprehenderit.",
                            title = "Frango",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("301fbfc7-4181-4df9-84f2-adae32b7bc43"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1751),
                            text = "Aliquam quos ut autem provident impedit alias ratione illum id.",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("c0ac0e98-3f86-455c-8638-d152beaed01d"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1806),
                            text = "quia",
                            title = "Bicicleta",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("1ff8edfa-15c6-4f0f-b527-87cf261e1ef4"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(1828),
                            text = "Natus voluptates voluptatum repellat a et nihil omnis provident. Labore voluptatum ut. Doloremque sint repellendus tenetur commodi illum voluptatem quae quisquam autem. Id deserunt quia eveniet praesentium quia. Debitis ut et qui.",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("d0777547-3f24-49a6-88c7-d61f85d6b0c8"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2065),
                            text = "quaerat",
                            title = "Sabonete",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("fe264cf8-3377-445c-aada-54ce79a98e43"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2094),
                            text = "Incidunt corrupti sit ullam illo necessitatibus aut. Delectus voluptatem blanditiis autem incidunt sed ut saepe similique. Maxime possimus dolores voluptas et et fuga maiores.",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("4577e145-1057-4d8a-8380-52c6a74167ad"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2197),
                            text = "aut",
                            title = "Bicicleta",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("09186220-6ae8-4bd0-bc33-93a544f45a6a"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2220),
                            text = "Facere quo voluptatem et ut eum.",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("32406b4b-8f06-4aa6-9229-385a9556d13b"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2260),
                            text = "et",
                            title = "Bacon",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("8bf50c30-66b0-459b-b82d-3985528dd095"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2283),
                            text = "Iste aliquid voluptatibus magnam rerum pariatur. Repellendus veritatis tempora rerum. Quo reiciendis repudiandae. Ut voluptas exercitationem.",
                            title = "Sapatos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("15331962-ff03-4310-941c-8ed517606f11"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2422),
                            text = "Tempore est aliquam sed.\nMolestias officia consequuntur ipsam hic aperiam veritatis quisquam quos.\nRerum vel enim.\nQui aut illum sunt perferendis iusto exercitationem cum.\nEst sed sint laboriosam.\nEt laboriosam sit doloremque consequatur quo veniam sed animi.",
                            title = "Mesa",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("59a09fb0-8130-423b-93d2-b98cf19b9f08"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2610),
                            text = "Repudiandae voluptates omnis consequatur praesentium inventore.",
                            title = "Atum",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("2cdee930-196a-4817-b32d-c18c15fc3f41"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2653),
                            text = "Quisquam dicta dolore occaecati explicabo tempora ullam. Qui repellendus et fugiat sunt sit velit iusto dolore. Aperiam quisquam neque dolore voluptatum voluptas excepturi repellat et.",
                            title = "Bacon",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("b287564e-559a-4a1b-9c04-31a47af7fa92"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2758),
                            text = "Quibusdam explicabo est magni commodi autem.\nNam ipsa ut voluptatem animi et ea quam et.\nFugit earum et.",
                            title = "Luvas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("d643fa4b-ee51-4b97-b76c-e60a23d4ac0f"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(2884),
                            text = "Qui soluta aut est sint ex perferendis nemo est. Accusantium consequuntur rerum laboriosam. Sint quia aliquid error enim eligendi. Vel non maiores voluptatem commodi. Voluptatem dolor facilis corrupti recusandae inventore qui qui vitae.",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("97608d30-4866-4435-90d4-4c1912976935"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3014),
                            text = "Est alias autem.\nAtque dignissimos cumque illo doloremque sit.",
                            title = "Teclado",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("20bff2d9-1f94-4c10-af5c-42ff3530b327"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3132),
                            text = "est",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("e084f2f5-bd23-4325-888f-aa2c2925d7c1"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3155),
                            text = "Quaerat minima quia quis qui inventore delectus animi earum sapiente.",
                            title = "Mouse",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("dd466e6a-973f-4746-9c3f-ef62f9bec847"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3211),
                            text = "Nihil possimus maxime soluta assumenda tenetur quas sit id sequi. Autem dolores quaerat quibusdam facilis voluptatem est quae. Et veritatis laboriosam veritatis quia nesciunt omnis. Fugiat ut ad ut optio eos est iusto modi. Vel cum consectetur quas. Pariatur expedita sint magnam.",
                            title = "Sapatos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("c3d4ac50-3ee8-4ca6-984e-c4465e73963b"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3404),
                            text = "suscipit",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("951dc57d-f739-414b-aee1-79c3b31d5f34"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3427),
                            text = "Error vero dolorem id quos omnis iusto perspiciatis voluptas doloribus.\nEst vitae a eum ipsum est.\nFacere autem soluta.\nVoluptas molestias dolor et accusantium quod animi nihil fugit.\nSed et minima rem accusantium voluptatem voluptas optio.\nSuscipit sint omnis neque maxime omnis.",
                            title = "Toalhas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("3fa5804b-02e6-4198-b84d-50257a0d3a2c"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3613),
                            text = "Occaecati harum molestias ex quibusdam. Expedita quia omnis dolorum voluptatem explicabo velit id earum voluptatibus. Provident nam hic modi velit. Magni similique ducimus qui ipsam. Corrupti eos eum.",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("2f60ed98-2cc6-4d77-a251-d3ee625232d2"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3728),
                            text = "Non aut ut nobis quia facere ipsam.\nSint voluptas voluptatum non fugiat vero molestias ex.",
                            title = "Cadeira",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("c3b6dc3f-4e2f-465e-95f2-7926a85be227"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3821),
                            text = "Alias ex itaque et in veniam quidem et et.\nVeniam dicta enim recusandae est quos et.\nIure dolorem perspiciatis.\nSit deleniti eum quia.\nSed quia at voluptatum perferendis quo rerum vitae placeat.\nEt tempora sapiente ipsa voluptatem velit doloribus eum nulla.",
                            title = "Sabonete",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("426d835d-2044-4a13-979d-42fef02a6478"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(3970),
                            text = "Voluptatum provident et dolorem accusamus.\nOfficiis harum quibusdam officiis sunt officia animi.\nEt doloremque dolorem.\nDucimus alias ipsa odit aliquam omnis nobis illum.\nIure facilis libero ipsum possimus accusantium consequatur laudantium sed.",
                            title = "Frango",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("9c4af3e4-8995-4192-ac90-90aa383d5e54"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4174),
                            text = "Eius rerum sed est nam.",
                            title = "Queijo",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("78598da3-28f6-41a6-98e7-5e1b2aa15226"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4214),
                            text = "quae",
                            title = "Bacon",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("0f32c95a-32d5-4e6c-91f5-36c44fb94271"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4237),
                            text = "Incidunt dolorem rerum perferendis cum ducimus.",
                            title = "Pizza",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("c42fe0b9-cd07-4870-a158-ded62b9f388b"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4326),
                            text = "Atque beatae provident optio et.",
                            title = "Calças",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("1edc3e87-7e9b-463f-b6da-802e4ba18ed1"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4364),
                            text = "Ut veniam placeat expedita impedit expedita minima dolores enim itaque.",
                            title = "Computador",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("5049baa5-c69c-4cf5-adde-289536921447"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4410),
                            text = "Ratione architecto voluptas soluta qui. Repellendus qui autem excepturi delectus laboriosam. Deleniti ex at illum maxime ut hic et aperiam quam. Libero facilis architecto id voluptatem voluptatem quae. Occaecati non eos et vel non asperiores est. Nemo est sunt.",
                            title = "Bicicleta",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("f62c9296-9cff-4a5c-b943-cc5c8a525a13"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4588),
                            text = "Deserunt quia ea sit quis qui nobis.",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("c5e78728-4629-4d4f-be64-bbecb9d0dd08"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4631),
                            text = "est",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("29830a2a-a961-4a0a-be03-9736d9171909"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4653),
                            text = "Nihil perspiciatis est enim deleniti et facilis. Explicabo placeat excepturi. Consequuntur animi magnam ut est voluptas pariatur quia.",
                            title = "Pizza",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("91325f32-fa2c-4f1d-8ccf-f5eb249103af"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4735),
                            text = "Corporis ratione nostrum recusandae dolor laboriosam voluptate qui velit ex. Eveniet et esse omnis excepturi omnis ipsa. Praesentium dolorem eum velit libero id modi in doloribus eos. Et at temporibus provident magnam distinctio.",
                            title = "Atum",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("8e41262d-a705-48c5-9482-876e9345793b"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4907),
                            text = "Et nostrum est quia maiores et ut quis dolorem.",
                            title = "Queijo",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("1cf90d70-8b9c-47d6-8a84-d0c0c5980c75"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4952),
                            text = "Assumenda consectetur aliquid sequi.",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("0ae633ea-9401-4070-9233-3dc64a9faef0"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(4985),
                            text = "Aut rem est voluptates et ratione accusantium quisquam quibusdam.\nId fugiat dolores.\nEaque fuga ratione illum non.\nQuibusdam qui quas eius nihil aliquam consectetur in.\nSit dolorum et vel sed dolorum magnam quis et sed.\nVoluptatem rerum accusamus debitis omnis perferendis distinctio id.",
                            title = "Luvas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("32cfcdd7-3f6f-4dc1-a118-a4ae000279af"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5175),
                            text = "Architecto est odio modi. Ut soluta et et repellendus beatae ut. Eos reprehenderit numquam quis eius sed mollitia cum magnam. Nesciunt sit est veniam minima enim ex voluptates.",
                            title = "Mesa",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("8af5edf8-46b5-4bd2-95fd-1b751388315b"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5316),
                            text = "Quis deserunt qui facilis molestias fuga autem.\nUt quod tenetur saepe.\nCupiditate incidunt rerum rerum totam officia enim quia.\nOmnis molestias eaque rerum aut tempore laboriosam earum.\nRepellendus consequatur deserunt dignissimos.\nOmnis recusandae voluptatem.",
                            title = "Computador",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("bff1de6d-ef65-43e8-b4dd-284842fe4d00"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5502),
                            text = "Impedit iste sed in tempora voluptate iste. Sunt amet non repudiandae ea sed. Nulla eum debitis. Dolores quia delectus. Provident ut iste aut expedita quaerat. Quia laborum veritatis beatae.",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("5beba8f3-6602-4479-877f-0584f93f4659"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5621),
                            text = "Qui veniam magni voluptates.",
                            title = "Mesa",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("2308a1f8-5516-492a-ae89-8216083f9ab1"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5655),
                            text = "Molestiae aut dignissimos ut architecto enim eum odit beatae hic. Sed commodi mollitia id pariatur sunt doloremque. Libero velit ducimus dolorem. Doloremque est est veritatis vel qui quaerat. Excepturi deserunt totam asperiores dolorem id praesentium.",
                            title = "Cadeira",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("12ee3597-bd41-47dd-b5fe-38c9aae92565"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5819),
                            text = "Libero aut omnis doloremque fugiat facere quaerat vitae sunt qui.",
                            title = "Pizza",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("e5fb2a23-d171-47a9-a95c-6728734cff40"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5865),
                            text = "illo",
                            title = "Cadeira",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("8754fb98-8b84-4e80-b662-c38a00a0a7e8"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5888),
                            text = "Id possimus voluptas sed et quasi non ut consequatur dignissimos.",
                            title = "Teclado",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("80638029-32cc-4e71-8d24-3b91de6123b7"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(5974),
                            text = "Quia molestias ut ut unde.\nEst ducimus cum dicta dolores.\nEarum deleniti nam repudiandae cupiditate illo praesentium nesciunt.\nEnim sit nam rerum.\nSaepe quidem odio tempora praesentium culpa quis quae iste laboriosam.\nArchitecto est temporibus.",
                            title = "Calças",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("5cc9aa91-6d62-44f7-baaa-407c8dde70da"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6105),
                            text = "Nihil enim eaque exercitationem molestiae corporis.\nDebitis exercitationem voluptatum repudiandae nam quidem.\nVoluptatem nihil rem neque.\nEst enim est.\nIste maiores quaerat ut unde.\nVoluptatum repudiandae officia minus sapiente eos impedit qui.",
                            title = "Sapatos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("01bfe07e-e17a-4903-879b-cb2d898f7d17"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6272),
                            text = "deserunt",
                            title = "Atum",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("850adbb8-ba01-454a-9330-74cd36fa0569"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6296),
                            text = "Perspiciatis minima est iure non quo saepe praesentium. Voluptatem sint nisi. Molestiae harum perferendis alias nisi rerum sit cupiditate velit laboriosam. Neque inventore alias vero deleniti accusantium eveniet ut officia aut. Non ut quis.",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("54e61827-7575-451c-ba1e-f6cdcbce29aa"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6443),
                            text = "dolor",
                            title = "Salgadinhos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("51b04538-5a8f-4d63-ad8b-0ab68641602e"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6465),
                            text = "Sed nobis facilis maxime deserunt.",
                            title = "Cadeira",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("0378ec22-9db5-465b-a938-898079c4054d"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6501),
                            text = "qui",
                            title = "Pizza",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("19c89f14-02a7-4183-ac74-de9371448f5a"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6523),
                            text = "Quos deserunt consequatur laudantium voluptatem debitis sit rerum qui.",
                            title = "Teclado",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("d6b18881-22b0-4598-aa76-a74ba256f3d4"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6569),
                            text = "Deserunt molestias aut quaerat.\nIste ipsa voluptates et velit sequi assumenda non.\nCumque soluta qui iure voluptatibus dolore.\nExplicabo ipsa quod quasi consequatur.",
                            title = "Salada",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("632d215d-3613-4f7a-acf8-0ec876fd1a86"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6769),
                            text = "quos",
                            title = "Mouse",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("69a9a69e-aca7-4a4b-b3fb-02f092746a20"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6792),
                            text = "Modi nisi reiciendis ut.",
                            title = "Luvas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("cb1025f9-ef7a-45ac-bf18-548cd67324eb"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6827),
                            text = "Repellat in ex velit.",
                            title = "Calças",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("7c27dcb6-7071-4b37-bc66-adfc00660308"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6861),
                            text = "Sapiente porro porro dolores.",
                            title = "Bola",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("410eabd8-ef18-4da5-b319-d93090769b9c"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6895),
                            text = "iure",
                            title = "Sabonete",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("a29a34a9-b905-4a38-965e-0562630f8aae"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(6965),
                            text = "Sed porro saepe ratione et accusantium dicta id. Quod magni et dolore molestias. Doloremque quia quidem modi non. Ipsa odit vitae ut iusto tempora incidunt sit quis. Perferendis itaque et eum sit.",
                            title = "Pizza",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("f64500b4-3a62-436d-ae42-5608ec8b69af"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7084),
                            text = "Et omnis dolores.",
                            title = "Chapéu",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("ae836eba-0247-4b3b-84cb-172e00e1a5d1"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7116),
                            text = "Sit sapiente adipisci vero possimus doloremque ea.\nSunt laborum optio dolore.\nSunt rerum rerum et enim eum nemo eligendi sequi omnis.\nVeritatis nam vel.",
                            title = "Luvas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("7eebc791-affb-4aac-a061-cd5c471a02e5"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7249),
                            text = "Et voluptatem molestiae temporibus esse quaerat ipsam.",
                            title = "Pizza",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("e84ac444-3069-4e65-b41f-8e488d2f8df2"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7290),
                            text = "Rem voluptas nobis officiis tempora cum.\nDolor tempora voluptates occaecati sint sed qui qui voluptatibus et.\nOmnis dolores repellat animi.\nAliquid atque ut nobis est voluptatem aut aut numquam nihil.",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("d3449893-bf48-44d1-8125-198a46438738"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7433),
                            text = "Qui enim nisi quaerat est. Dicta excepturi et saepe et. Ipsum veritatis accusamus id deleniti. Consequatur sunt facere consequatur eius non.",
                            title = "Cadeira",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("a5708d7d-466d-48dd-8251-aff6dedb4284"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7524),
                            text = "Unde omnis qui fugiat et aut dolore. Voluptatem numquam eum dolorum quia harum placeat ea ipsa consectetur. Accusantium distinctio molestiae qui libero. Saepe sed quis ut nostrum ut alias officia nulla. Quis nihil voluptas accusantium odit corrupti similique explicabo minus. Vero rerum ut vel repellendus in voluptatem maiores sed temporibus.",
                            title = "Toalhas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("36891574-be22-45c4-aa8d-a03056dfed8f"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7727),
                            text = "Minima impedit et.\nEt est est voluptatibus molestiae expedita perferendis deleniti sint quibusdam.\nBeatae voluptate sit qui saepe eligendi quia.\nSit est ut.",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("e240da33-7418-41d7-847d-c28e39bd6491"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7821),
                            text = "Nobis vel ut exercitationem nostrum.",
                            title = "Mesa",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("107f2303-d20f-42cd-8423-68a406917868"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7895),
                            text = "Quia modi velit et deleniti cumque.",
                            title = "Camiseta",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("acd5c05e-9042-4bfc-8903-344ad652a94b"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(7933),
                            text = "Nemo maiores quidem earum. Aliquid velit error ut amet repellendus autem aut ut dolorem. Ratione ipsum a eaque quis. Praesentium laudantium perspiciatis consequatur. Autem eaque totam reiciendis mollitia reprehenderit.",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("f007b8a1-f139-4402-a1f1-5684e74d5d50"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8045),
                            text = "Quia perspiciatis provident soluta.\nVoluptatem ullam voluptas vel unde.\nProvident maiores similique.\nIpsum dolorem aliquam alias illum fugiat rerum suscipit nobis expedita.",
                            title = "Toalhas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("8afa6884-2cb1-4768-9c7a-d3a686bd0e81"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8173),
                            text = "Alias ex optio occaecati dolor esse corrupti accusantium velit.\nNon quia qui quae quia amet facere ipsum possimus.\nEarum magni sint numquam voluptatem ut cumque sed.",
                            title = "Salsicha",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("bd39160f-c443-4986-9b81-4fc0b405b34c"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8268),
                            text = "Recusandae accusamus optio perferendis assumenda et.",
                            title = "Sapatos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("eaf6123f-5e1a-499c-bcf4-1db877f42348"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8327),
                            text = "Aut vitae in quidem quos voluptatibus accusantium adipisci.\nOptio explicabo ipsa ad quia sunt.\nEt qui nihil.",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("71e4061b-80ff-4f76-8796-2330f6247742"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8402),
                            text = "Necessitatibus dolorem sit. Unde aut nesciunt sint et. Doloremque repellendus quod nihil. At ex voluptas sit magnam voluptatem qui. Voluptatem sed inventore quis debitis. Aliquam aut autem eligendi in.",
                            title = "Salsicha",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("fd83252f-ad01-426e-906a-b04a1b11d8f7"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8615),
                            text = "officia",
                            title = "Peixe",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("e42fc11b-6242-40cc-bc56-3ae0fbd2c671"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8641),
                            text = "voluptatem",
                            title = "Queijo",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("b5e9dc2f-dac0-4ad5-a939-37e9d4652ddb"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8663),
                            text = "Sit vel vero omnis ullam at dolore quasi.\nQuas rerum at dicta nihil eum facilis.",
                            title = "Bacon",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("78ff61c2-ff9b-4eda-8b5a-69af4f349017"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8730),
                            text = "Enim unde repellat quis. Et ut fugiat provident officia reprehenderit aut temporibus. Ut eos incidunt excepturi maiores qui. Facilis autem eos cumque numquam eaque. Et hic sed.",
                            title = "Toalhas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("65f00069-c803-4b87-abf7-665da7cccaaa"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8888),
                            text = "molestiae",
                            title = "Bacon",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("04b641bc-9263-486a-b017-6e2423843566"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(8911),
                            text = "Quis exercitationem fugiat modi ipsum rerum. Voluptates atque veniam voluptas. Doloremque ullam voluptas nisi est. Maiores ullam aliquam id rerum alias quae.",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("eafc3a75-af4d-4e28-9db5-9e55baac2465"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9002),
                            text = "Sint et fugiat velit modi. Libero voluptas nobis omnis a aliquid omnis. Sint qui et quia sint est voluptatem.",
                            title = "Carro",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("8b372ff9-5b79-4510-91b0-29f30f0bfa3c"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9118),
                            text = "Ea earum maxime quidem deleniti voluptatem voluptatum quos ut.",
                            title = "Salgadinhos",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("e5e4d2ba-8350-4dac-b703-c89d0507a041"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9163),
                            text = "Ipsum non voluptates beatae saepe totam voluptatem.",
                            title = "Mouse",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("179d194f-0526-49f0-8417-ac4a547672d8"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9204),
                            text = "ut",
                            title = "Chapéu",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("814952fb-a755-4077-b2ac-1f53ae891b8d"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9226),
                            text = "itaque",
                            title = "Bicicleta",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("c5f7edff-c108-432a-924e-9138986921fc"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9248),
                            text = "Ratione est aspernatur.\nLaborum qui repudiandae similique commodi.\nTemporibus hic numquam maiores est qui laborum nulla voluptas incidunt.\nQuod nam enim consequuntur a reprehenderit.",
                            title = "Computador",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("9fee666a-f07f-4d0d-9416-9262816d2018"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9397),
                            text = "Dolorum voluptatem praesentium dignissimos voluptatem ipsa est debitis et. Quae voluptas nostrum magnam alias id hic autem ea. Aut temporibus dolore excepturi autem et accusantium voluptatem et. Et explicabo ut blanditiis non. Voluptatibus qui labore non nam ea eligendi ut.",
                            title = "Mouse",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("f95299cb-24d7-46f5-88f5-91cd80fdfdc0"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9570),
                            text = "Eaque nam rerum non porro. Deleniti ad provident excepturi maxime. Quaerat sit architecto occaecati ea. Et labore voluptatum cumque iste aut aut. Quidem aut nisi a nemo fugiat accusamus. Quis accusamus explicabo perferendis ut beatae adipisci ipsam voluptas et.",
                            title = "Calças",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("3c726b66-ef36-4bbc-b2fc-fbb8d3e2200e"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9711),
                            text = "Mollitia numquam inventore voluptas qui harum est.",
                            title = "Luvas",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        },
                        new
                        {
                            id = new Guid("deb79d32-a525-4cff-9785-56dd941ed355"),
                            acesses = 0,
                            created_at = new DateTime(2024, 1, 28, 11, 35, 9, 663, DateTimeKind.Local).AddTicks(9786),
                            text = "Excepturi perferendis quas quae omnis ipsam suscipit fugit est.\nQuod ab doloremque et sint voluptatem sint culpa.\nEligendi unde quae provident ex cupiditate quae id aliquid.",
                            title = "Atum",
                            userId = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb")
                        });
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Subscriptionplan", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("Date");

                    b.Property<int>("months")
                        .HasColumnType("integer");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("subscriptionplans");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("cpf")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("Date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("github")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("phoneNumber")
                        .HasColumnType("integer");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.Property<string>("socialNetwork")
                        .HasColumnType("text");

                    b.Property<Guid?>("subscriptionplanId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("subscriptionplanId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            id = new Guid("0a279b42-af37-41e6-80b9-d43a1d5942cb"),
                            cpf = 0,
                            createdAt = new DateTime(2024, 1, 28, 11, 35, 9, 662, DateTimeKind.Local).AddTicks(6011),
                            email = "admin@admin.com",
                            is_active = true,
                            name = "admin",
                            role = 2
                        },
                        new
                        {
                            id = new Guid("b1d2fb65-713b-426c-8e2a-9ece4b36b4fb"),
                            cpf = 0,
                            createdAt = new DateTime(2024, 1, 28, 11, 35, 9, 662, DateTimeKind.Local).AddTicks(6135),
                            email = "user@email.com",
                            is_active = true,
                            name = "user",
                            role = 2
                        });
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("Date");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("duration")
                        .HasColumnType("text");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<string>("videoUrl")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("moduleId");

                    b.ToTable("videos");
                });

            modelBuilder.Entity("ModuleProgress", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("courseProgressId")
                        .HasColumnType("uuid");

                    b.Property<bool>("done")
                        .HasColumnType("boolean");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("courseProgressId");

                    b.HasIndex("moduleId");

                    b.ToTable("moduleProgresses");
                });

            modelBuilder.Entity("VideoProgress", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("moduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("videoId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("moduleId");

                    b.HasIndex("videoId");

                    b.ToTable("VideoProgresses");
                });

            modelBuilder.Entity("CourseProgress", b =>
                {
                    b.HasOne("GenericCourses.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericCourses.Domain.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("user");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Category", b =>
                {
                    b.HasOne("GenericCourses.Domain.Entities.Course", null)
                        .WithMany("categories")
                        .HasForeignKey("Courseid");

                    b.HasOne("GenericCourses.Domain.Entities.Post", null)
                        .WithMany("categories")
                        .HasForeignKey("Postid");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.User", b =>
                {
                    b.HasOne("GenericCourses.Domain.Entities.Subscriptionplan", "subscriptionplan")
                        .WithMany("users")
                        .HasForeignKey("subscriptionplanId");

                    b.Navigation("subscriptionplan");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Video", b =>
                {
                    b.HasOne("GenericCourses.Domain.Entities.Module", null)
                        .WithMany("videos")
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModuleProgress", b =>
                {
                    b.HasOne("CourseProgress", "courseProgress")
                        .WithMany()
                        .HasForeignKey("courseProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericCourses.Domain.Entities.Module", "module")
                        .WithMany()
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courseProgress");

                    b.Navigation("module");
                });

            modelBuilder.Entity("VideoProgress", b =>
                {
                    b.HasOne("GenericCourses.Domain.Entities.Module", "module")
                        .WithMany()
                        .HasForeignKey("moduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericCourses.Domain.Entities.Video", "video")
                        .WithMany()
                        .HasForeignKey("videoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("module");

                    b.Navigation("video");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Course", b =>
                {
                    b.Navigation("categories");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Module", b =>
                {
                    b.Navigation("videos");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Post", b =>
                {
                    b.Navigation("categories");
                });

            modelBuilder.Entity("GenericCourses.Domain.Entities.Subscriptionplan", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
